CREATE TABLE [dbo].[ControlTable](
	[SourceObject] [varchar](50) NOT NULL,
	[LastLoadDate] [datetime] NULL,
 CONSTRAINT [PK_ControlTable] PRIMARY KEY CLUSTERED 
(
	[SourceObject] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

